module Constants
  	CAMP_SAVED = 0
	CAMP_COMPLETED = 1
	CAMP_QUEUED = 2
	CAMP_INPROGRESS = 3

	RESP_CANCELLED = -2
	RESP_FAILED = -1
	RESP_SAVED = 0
	RESP_SENT = 1
	RESP_QUEUED  = 2
	RESP_SENDING = 3
end